# Generated by Django 5.1.1 on 2024-10-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0004_alter_products_discount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={
                "ordering": ["id"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
    ]
